layout: default
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 6
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  website: https://HeyRoseKay.com
  dribbble: HeyRoseKay
  linkedin: HeyRoseKay
  instagram: HeyRoseKay
  twitter: HeyRoseKay
  # behance: your_username
  # facebook: your_username
  # hackerrank: your_username
  # keybase: your_username
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # unsplash: your_username
  # vk: your_username
  # youtube: your_username

topics:
  - name: Swift
    web_url: https://github.com/topics/swift
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/swift/swift.png

  - name: Apple Platforms
    web_url: https://developer.apple.com/discover/
    image_url: https://i.pinimg.com/originals/2d/51/e8/2d51e815a33e0503a15056f62586933a.png

  - name: Sketch
    web_url: https://github.com/topics/sketch
    image_url: https://raw.githubusercontent.com/github/explore/a5995564b5ff71c41da080abc49f1ba4132127c1/topics/sketch/sketch.png
